spring:
  datasource:
    username: ahmed
    password: ahmed
    url: jdbc:mysql://localhost:3306/sport?useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090
